kii/kii.h, kii/kii_ti.c, tio/include/tio2.h
- モジュールの名前空間の変更: `kii_thing_if` -> `tio`
- `Command handler`と`State updater`を`thing_if_t`にまとめていたが、`thing_if_t`を廃止して別々のモジュールとして表現するようにした。
- `Command handler`だけ実行, `State updater`だけ実行、両方実行する等の制御が可能。
- 分けることでAPIが明快になった
- thing-ifのAPIを実行する機能を`kii`モジュール に移行した。
- cloud/ thing-ifのREST APIは共通部分が多いので同じモジュールのほうが良い。
=> thing-if module renewal

khc/src/khc_impl.c, tests/large_test/khc/post_test.cpp, tests/small_test/khc/minimal_test.cpp
Call `KHC_CB_READ` until it returns 0.
Expecting requested size to be read at once was wrong assumption in general. (ex. Data source is socket.)
Ref: https://curl.haxx.se/libcurl/c/CURLOPT_READFUNCTION.html
=> Fixed Read Callback handling

kii/kii.h, kii/kii_ti.c, kii/kii_ti_impl.c, kii/kii_ti_impl.h, tests/large_test/kii/ti_test.cpp, tio/tio.c
By default `kii_ti_put_state` handles multiple trait state. Enable to send non-trait state by specifying content-type (application/json)
The reason of not using boolean parameter to switch fixed content-type is foreseeing the introduction of new content-type as now we have normalizer which preprocess the state.
=> Specify content-type of put state.

kii/kii.h, kii/kii_object.c, kii/kii_object_impl.c, kii/kii_object_impl.h, kii/kii_ti.c, kii/kii_ti_impl.c, kii/kii_ti_impl.h, tests/large_test/kii/object_test.cpp, tests/large_test/kii/ti_test.cpp, tio/tio.c
Removed content-length argument from APIs.
No need to give Content-Length beforehand since we're using chunked transfer encoding now.
=> Http1.1 api change

khc/include/khc.h, khc/include/khc_socket_callback.h, khc/src/khc.c, khc/src/khc_state_impl.c, kii/kii.c, kii/kii.h, kii/kii_mqtt.c, tests/large_test/khc/get_test.cpp, tests/large_test/khc/post_test.cpp, tests/large_test/kii/large_test.h, tests/large_test/secure_socket_impl.cpp, tests/large_test/secure_socket_impl.h, tests/small_test/khc/.gitignore, tests/small_test/khc/response_chunk_test.cpp, tests/small_test/khc/response_test.cpp, tests/small_test/khc/state_trans_test.cpp, tests/test_callbacks.h, tio/README.md, tio/include/tio.h, tio/linux-sample/example.c, tio/linux-sample/sock_cb_linux.c, tio/linux-sample/sock_cb_linux.h, tio/tio.c
Enable to set socket timeout.
Aiming to fix #51, but it is not only for this.
Setting timeouts by clients should be allowed to control the maximum wait time.
=> Introduced timeouts for recv/ send data from socket.

khc/include/khc.h, khc/src/khc.c, khc/src/khc_slist.c, kii/kii.c, kii/kii.h, kii/kii_api_call.c, kii/kii_req_impl.c, tests/small_test/khc/slist_test.cpp, tio/include/tio.h, tio/tio.c
Fixed #42
`void tio_handler_set_slist_resource_cb()` , `void tio_updater_set_slist_resource_cb()` 
がそれぞれ `tio_handler_set_app()`, `tio_updater_set_app()` の後にコールする必要がある問題は、別のPRで対処する。
https://github.com/KiiPlatform/ebisu/issues/65
=> Enable to use custom allocator of khc_slist.

khc/include/khc.h, kii/kii.c, kii/kii.h, tio/include/tio.h, tio/tio.c
kii/ tio にStream/ Header用のバッファを設定するAPIを追加しました。 (#42)
- Stream/ Header用のバッファの設定は任意のままとし、設定が無い場合はmallocする処理は残しました。
これは設定を強制にすると設定が必要なバッファ(JSONの構築・パース用、MQTTのメッセージパース用、Stream, Header)が多くなってしまい、malloc/freeが許容できる環境では煩雑となるためです。
- tio のバッファの開放についてはtaskを安全にterminateする手段が必要ですが、その手段の提供は #47 で行います。
=> Stream/ Header buff setters

khc/src/khc_state_impl.c, tests/small_test/khc/response_test.cpp, tests/small_test/khc/state_trans_test.cpp
KHC_CB_READが設定されていない場合は `Content-Length: 0` を出してリクエストボディの要求をしないように状態遷移を修正しました。
レビューをお願いします。
スモールテストの方は、チャンクを想定してないテストではリクエストもチャンクではないように変更しています。
Issue: #35
=> Add check _cb_read is NULL or not.

khc/include/khc.h, khc/src/khc.c, kii/kii.c, kii/kii.h
`kii` `khc` のセッターで値を返す必要のないものを修正しました。
`jkii` `tio` では対象はありませんでした。
一部ドックコメントでreturn typeが間違っていたのがあったので合わせて修正しています。
注意: PR: #79 マージ後、ベースブランチを `http1.1` に変更が必要。
Issue: #69
=> change setter return type to void.

tio/include/tio.h, tio/tio.c
tio_handler_t/ tio_updater_t の各パラメータをinitで初期化するように修正しました。レビューをお願いします。
tio_handler_t の _http_buff/ _mqtt_buff は現在どこからも使われていない(バッファを直接kiiにセットするようになったため)ので削除しています。
Issue: #76
=> Initialize parameters in tio_*_init.

jkii/include/jkii.h, jkii/src/jkii.c, khc/include/khc.h, khc/src/khc_slist.c, kii/kii.c, kii/kii.h, kii/kii_api_call.c, kii/kii_json_wrapper.c, kii/kii_req_impl.c, kii/kii_task_callback.h, tests/large_test/kii/large_test.h, tests/small_test/jkii/src/jkii_test.cpp, tests/small_test/khc/slist_test.cpp, tio/README.md, tio/command_parser.c, tio/command_parser.h, tio/include/tio.h, tio/tio.c
`cb_{}` , `{}_cb` のパターンが混在していたので、 `cb_{}` に統一しました。
=> Renamed callback related APIs

kii/include/kii.h, kii/kii_req_impl.c, kii/kii_req_impl.h, kii/kii_ti.c, kii/kii_ti_impl.c, kii/kii_ti_impl.h, tests/large_test/kii/ti_test.cpp, tio/tio.c
`Content-Encoding` header is required when upload compressed data to data normalizer, like `Content-Encoding: gzip`. 
In this PR, the following changes are performed:
- add `opt_content_encoding` parameter to `kii_put_state`
- add content_encoding handle logic
- add `opt_content_encoding` parameter to `kii_put_bulk_states`, `kii_patch_state` and `kii_patcth_bulk_states`
- implement `kii_put_bulk_states`, `kii_patch_state` and `kii_patcth_bulk_states`.
=> Add content-encoding for thing state APIs thru data normalizer

jkii/include/jkii_utils.h, jkii/src/jkii.c, tio/cc3200-sample/main.c, tio/command_parser.c, tio/gt202-sample/tio_demo.c, tio/include/tio.h, tio/linux-sample/example.c, tio/tio.c, tio/wiced-sample/tio_demo.c
TIO_CB_ACTIONでaction_resultのdataを設定できるように修正しました。レビューをお願いします。
`_parse_command` 呼び出しの所は警告が出てたので一緒に直しています。
Issue: #123
=> Impl action result data

khc/src/khc.c, khc/src/khc_state_impl.c, khc/src/khc_state_impl.h, tests/small_test/khc/state_trans_test.cpp
#134 
We decided to move the allocation and free logic to `khc_perform` so that it can become easy to maintain.
=> Free allocated resource in finished state

khc/src/khc.c
khc->_resp_header_buff がリークする可能性があったので修正しました。マージをお願いします。
=> fix memory leak in _stream_buff allocate failed.

tests/large_test/kii/Makefile, tests/large_test/kii/README.mkd
新規アプリを用意して以下のようにするとテストに必要なリソースを作ってくれるスクリプトを追加しました
```
$ cd tests/large_test/kii/
$ DEFAULT_SITE="${DEFAULT_SITE}" \
APP_ID="${APP_ID}" \
CLIENT_ID="${CLIENT_ID}" \
CLIENT_SECRET="${CLIENT_SECRET}" \
make initapp
```
=> add init target for non-default app

tests/large_test/kii/Makefile, tests/large_test/kii/README.mkd, tests/large_test/kii/api_call_test.cpp, tests/large_test/kii/large_test.h
QA team wants to run large test for ensuring varnish-to-openresty transition is OK for ebisu.
=> added macro var to override app-id and api host

kii/kii_ti_impl.c
Issue: #151 
送信の `thingProperties` が文字列になっていたのでObjectで送信されるように修正しました。
=> fix thingProperties type to Object.

tests/large_test/kii/ti_test.cpp
fixed timestamp is not acceptable after some time.
Fixes #162
=> Fix timestamp for generatedAt in tests

kii/include/kii.h, kii/kii_server_code.c
Server code API currently only allows to execute current version. This change adds the ability to execute a specific one.
=> Add ability to execute a specific server-code version
