KiiPlatform/ebisu

kii/kii_ti.c, kii/kii_ti_impl.c, kii/kii_ti_impl.h, tests/large_test/ti_test.cpp
kii_ti_put_firmware_versionとkii_ti_get_firmware_versionの実装とテスト作成を行いました。レビューをお願いします。
=> implement kii_ti_get_firmware_version and kii_ti_put_firmware_version.

kii_json/include/kii_json.h
Removed deprecated tag from the name field.
#12
=> Removed deprecated tag from the name field.

khc/src/khc_state_impl.c
エラーの際にresultが得られない件を修正しました。レビューをお願いします。
Issue: #45
=> fix for getting error result.

.circleci/config.yml, tests/small_test/khc/data/resp-login-chunked-headers.txt, tests/small_test/khc/http_test.cpp, tests/small_test/khc/http_test.h, tests/small_test/khc/response_chunk_test.cpp
ランダムにbuff_sizeを作るテストとChunkボディを作るテストを追加しました。レビューをお願いします。
Issue: #33
=> Add chunk response tests

khc/src/khc_state_impl.c, tests/small_test/khc/http_test.cpp, tests/small_test/khc/http_test.h, tests/small_test/khc/response_test.cpp
HTTPステータスが1xxだった場合にその部分を読み飛ばす処理とテストを追加しました。
レビューをお願いします。
Issue: #41
=> Ignore http status 1xx

khc/include/khc.h, khc/include/khc_socket_callback.h, khc/src/khc.c, khc/src/khc_state_impl.c, kii/kii_mqtt_task.c, tests/large_test/secure_socket_impl.cpp, tests/large_test/secure_socket_impl.h, tests/small_test/khc/response_chunk_test.cpp, tests/small_test/khc/response_test.cpp, tests/small_test/khc/state_trans_test.cpp, tests/test_callbacks.h
=> Add out sent length

tio/linux-sample/sock_cb_linux.c, tio/linux-sample/sock_cb_linux.h
修正漏れがありました。マージをお願いします。
Issue: #54
=> out_sent_lengthの修正漏れ対応.

kii/kii.c, kii/kii.h, tests/large_test/kii/large_test.h, tio/tio.c
=> separate kii_init.

kii/kii.h, kii/kii_ti.c, kii/kii_ti_impl.c, kii/kii_ti_impl.h
- add API to put bulk states: `kii_ti_put_bulk_states`
- add API to patch state: `kii_ti_patch_state`
- add API to patch bulk states: `kii_ti_patch_bulk_states`
=> Add upload thing state APIs

kii/kii.c, kii/kii.h, kii/kii_mqtt_task.c, kii/kii_push.c, kii/kii_task_callback.h, tio/include/tio.h, tio/linux-sample/example.c, tio/linux-sample/linux-env/task_impl.c, tio/linux-sample/linux-env/task_impl.h, tio/linux-sample/sys_cb_impl.h, tio/linux-sample/sys_cb_linux.c, tio/tio.c
`KII_TASK_CREATE` と `KII_DELAY_MS` に `userdata` を追加しました。レビューをお願いします。
`KII_TASK_CREATE` の定義で `param` と `userdata` が紛らわしかったので、 `entry` 用であることを明示するため `entry_param` へ変更しています。
Issue: #72
=> add userdata to KII_TASK_CREATE and KII_DELAY_MS.

tio/include/tio.h
Fix of #7.
- Other module (khc, jkii, kii) doxygen comments will be added/ fixed in separated PR.
- CI integration will be done when dealing with #31
=> Added doxygen comment to tio APIs

khc/src/khc_state_impl.c, tests/small_test/khc/response_chunk_test.cpp, tests/small_test/khc/response_test.cpp, tests/small_test/khc/state_trans_test.cpp
Issue: #82 
* KHCの異常系テストケースの追加
=> Add khc abnormal tests

tests/small_test/kii/mqtt_test.cpp
Issue: #82 
* KiiのMQTT周りの異常系テストケースの追加
=> add mqtt state abnormal tesets.

.circleci/config.yml, Makefile
Issue: #82 
* kiiのスモールテストをCircleCIで実施する
=> add stest-kii to circleci.

kii/kii_api_call.c, kii/kii_push_impl.c, kii/kii_req_impl.c, kii/kii_thing_impl.c, kii/kii_ti_impl.c, tio/linux-sample/example.h
Don't send content-length with `Transfer-Encoding: chunked`
=> Don't send Content-Length

khc/include/khc.h, khc/src/khc.c, khc/src/khc_state_impl.c, kii/include/kii.h, kii/kii.c, kii/kii_mqtt_task.c, tests/small_test/khc/state_trans_test.cpp, tests/small_test/kii/mqtt_test.cpp, tests/small_test/kii/simple_test.cpp, tests/small_test/tio/simple_test.cpp, tio/include/tio.h, tio/tio.c
=> Enable to choose insecure HTTP/ MQTT connection

khc/src/khc.c
_enable_insecureの初期化をkhc_initへ移動しました。確認とマージをお願いします。
=> fix _enable_insecure init tyming.

tio/wiced-sample/Makefile, tio/wiced-sample/tio_demo.c, tio/wiced-sample/tio_iot.mk, tio/wiced-sample/tio_socket_impl.c, tio/wiced-sample/tio_socket_impl.h, tio/wiced-sample/tio_task_impl.c, tio/wiced-sample/tio_task_impl.h, tio/wiced-sample/wifi_config_dct.h
WICED SDK v4.1系で動作確認したサンプルの追加です。レビューをお願いします。
SDKを6系に上げるかもしれないのでREADMEはまだ作成してません。
Issue: #121
=> WICED sample

tio/include/tio.h, tio/tio.c
=> Add tio_handler_handle_command api

tio/command_parser.c
=> fix actionResults for trait.

tio/command_parser.c, tio/command_parser.h, tio/include/tio.h, tio/tio.c
=> set action callback on tio_handler_handle_command.

kii/kii_object_impl.c, kii/kii_ti_impl.c
#137 
As mentioned in the comment: https://github.com/KiiPlatform/ebisu/issues/137#issuecomment-473226330
In this PR, fix the possible memory leakage.
=> Fix possible memory leak by using khc_cb_slist_alloc

tests/large_test/khc/Makefile, tests/large_test/khc/get_test.cpp, tests/large_test/khc/post_test.cpp, tests/large_test/kii/Makefile, tests/large_test/kii/large_test.h, tests/large_test/secure_socket_impl.cpp, tests/large_test/secure_socket_impl.h
in order to check actual HTTP traffics, it's handy to have plain http test.
=> added ability to execute large test with plain http

tests/large_test/kii/Makefile, tests/large_test/kii/README.mkd, tests/large_test/secure_socket_impl.cpp
https://github.com/KiiPlatform/ebisu/pull/146 がマージされたらbaseをmasterに変更する
SOCKET_LOGが定義されていたらsend/recvのタイミングでバッファをコンソールに出力するようにしました
サーバーとのやり取りが全て見えるのでテストのデバッグが楽になります
=> output socket buffer when SOCKET_LOG is defined.

kii/include/kii.h
=> remove kii_ti_put_thing_type declaration.

kii/include/kii.h, kii/kii.c, kii/kii_api_call.c, kii/kii_object_impl.c, kii/kii_push_impl.c, kii/kii_req_impl.c, kii/kii_req_impl.h, kii/kii_server_code.c, kii/kii_thing_impl.c, kii/kii_ti_impl.c, tests/small_test/kii/simple_test.cpp
add `kii-m: 0` flag and setter method to kii library.
Issue: #145
=> add kii-m header

.github/workflows/build.yml, .gitignore, jkii/CMakeLists.txt, khc/CMakeLists.txt, kii/CMakeLists.txt, tio/CMakeLists.txt, version/EbisuVersion.cmake, version/ebisu_version.h.in
Modifies the build system so that git tags are used as version numbers.
=> Versioning from GIT
